# Generated by Django 2.2 on 2020-06-05 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeSheetApp', '0009_auto_20200604_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='timeSheetApp.User'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='timeSheetApp.User'),
        ),
        migrations.DeleteModel(
            name='Add_Member',
        ),
    ]
