# Generated by Django 2.2 on 2020-06-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeSheetApp', '0010_auto_20200605_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='working_hours_end',
        ),
        migrations.RemoveField(
            model_name='user',
            name='working_hours_start',
        ),
    ]
